Repository opiproject/opi-poc, pull requests merged in 2022-07, with the labels that each got.

#121 spdk: Use multi-stage Docker build
  integration/docker-compose.spdk.yml
  integration/docker-compose.xpu.yml
  integration/scripts/integration.sh
  integration/spdk/Dockerfile
Labels: storage

#137 deploy: Add deployment script
  integration/scripts/deploy.sh
Labels: enhancement

#146 add healthcheck to spdk dockerfile
  storage/Dockerfile
Labels: docker, storage

#145 user pre-built storage image
  .github/workflows/poc-integration.yml
  integration/docker-compose.spdk.yml
  integration/docker-compose.xpu.yml
Labels: docker, storage

#157 storage: add cmd and port to dockerfile
  storage/Dockerfile
Labels: docker, storage

#177 tests: fix tftp always return 0
  integration/docker-compose.pxe.yml
  integration/scripts/integration.sh
Labels: bug

#172 build: Push storage container on PRs
  .github/workflows/poc-storage.yml
  storage/docker-compose.yml
Labels: CI

#217 storage-skip: Match job name
  .github/workflows/poc-storage-skip.yml
Labels: bug, CI

#222 security: Add strongSwan container to PoC
  integration/docker-compose.xpu.yml
  integration/scripts/integration.sh
  integration/strongswan/server/eap.conf
  integration/strongswan/server/ecdsa/serverKey.pem
  integration/strongswan/server/psk.conf
  integration/strongswan/server/rw.conf
  integration/strongswan/server/swanctl.conf
  integration/strongswan/server/x509/serverCert.pem
  integration/strongswan/server/x509ca/caCert.pem
  integration/strongswan/strongswan.conf
  integration/xPU-Integration-Blocks.png
Labels: security

#228 storage: split client into files
  storage/README.md
  storage/client/backend.go
  storage/client/client.go
  storage/client/frontend.go
  storage/client/middleend.go
  storage/docker-compose.yml
Labels: storage

#230 security: Add scaffolding
  .github/workflows/poc-security-skip.yml
  .github/workflows/poc-security.yml
  README.md
  security/Makefile
  security/README.md
  security/conf/client/eap-tls.conf
  security/conf/client/eap.conf
  security/conf/client/ecdsa/clientKey.pem
  security/conf/client/home.conf
  security/conf/client/psk.conf
  security/conf/client/swanctl.conf
  security/conf/client/x509/clientCert.pem
  security/conf/client/x509ca/caCert.pem
  security/conf/server/eap.conf
  security/conf/server/ecdsa/serverKey.pem
  security/conf/server/psk.conf
  security/conf/server/rw.conf
  security/conf/server/swanctl.conf
  security/conf/server/x509/serverCert.pem
  security/conf/server/x509ca/caCert.pem
  security/conf/strongswan-client.conf
  security/conf/strongswan-server.conf
  security/docker-compose.yml
Labels: security
